# SITE CONFIGURATION
title: Sciencmine 的博客 :: Minecraft # your site title
author: Sciencmine # You :P
description: > # Meta description of Homepage
  Sciencmine 的博客，Minecraft 分页，浅谈关于 Minecraft、模组等的一系列问题
baseurl: "/minecraft" # the subpath of your site, e.g. /blog
url: "https://sciencmine.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Sciencmine
  links:
    - https://github.com/Sciencmine

# THEME SETTINGS
navigation: # Navigation links
  - {name: '主页', link: '/'}
  - {name: '关于', link: '/about'}
  - {name: '联系', link: '/contact'}

tagline: >
  Sciencmine 的博客，Minecraft 分页

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: 2631197967@qq.com # email for form submission
form_endpoint: mbjldjby

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  Sciencmine # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  #shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
